@startuml

actor User
participant Service
database Database

User -> Service: send valid username
Service --> User: Reset token
Service -> Database: Store reset token for user
User -> Service: Send reset token + username
Service -> Database: Compares tokens
Service -> Database: Update password

@enduml