#!/usr/bin/with-contenv bash

cred_file="/etc/guacamole/user-mapping.xml"

if [[ -n "$GUAC_USER" ]]; then
  sed -i -e s%"\(username\=\).*"%"\1\"$GUAC_USER\""%g "$cred_file"
fi

if [[ -n "$GUAC_PASS" ]]; then
  sed -i -e s%"\(password\=\).*"%"\1\"$GUAC_PASS\""%g "$cred_file"
fi

if [[ ! -n "$GUAC_USER" ]] && [[ ! -n "$GUAC_PASS" ]] && [[ ! -f /etc/guacamole/noauth-config.xml ]]; then
  mv /defaults/noauth-config.xml /etc/guacamole/
  mv /defaults/guacamole-auth-noauth-*.jar /etc/guacamole/extensions/
  echo 'noauth-config: /etc/guacamole/noauth-config.xml' >> /etc/guacamole/guacamole.properties
fi